/**
 * political_data.json + the party-emblem manifest — the same two static files
 * the website reads. Fetched once per app run and memoised: the data changes on
 * the order of weeks, and three screens want it.
 */
// Same override as lib/api.ts, and for the same reason: in a browser these two
// fetches are cross-origin and production blocks them. See the note there.
const BASE = process.env.EXPO_PUBLIC_API_BASE || 'https://hawkeye.com.ng';

export type Candidate = {
  name: string;
  party: string;
  initials?: string;
  line?: string;
  home?: string;
  bids?: string;
  status?: string;
  incumbent?: boolean;
  photo?: string;
};

export type Minor = { name: string; party: string; meta?: string };

/**
 * Where a race sits on the map — the same block app/race.js reads.
 *
 * A race declares its own seat, so the region -> race-page index can be derived
 * rather than kept as a second list beside the data. `level` picks the geometry:
 * a governorship is a `state` (drawn as its LGAs), a Senate seat is
 * `senatorial`, a House seat `federal_constituency`.
 */
export type RaceJoin = {
  contest?: string;
  /**
   * `lga` is the STATE-ASSEMBLY level. State constituencies are not a column in
   * the electoral register — which is why the backend buckets an SHA contest's
   * reports by LGA — so an assembly seat's map, board and scope all key on the
   * LGA it sits in. There is no outline file for one, and there cannot be.
   */
  level: 'state' | 'senatorial' | 'federal_constituency' | 'lga';
  value: string;
  state?: string;
  lgas?: string[];
};

export type Race = {
  asOf?: string;
  office?: string;
  election?: string;
  date?: string;
  /** Verbatim date label when there is no fixed ISO date yet (e.g. the 2027
   *  presidential day, shown as dateText "2027" / dateLabel "Election year"). */
  dateText?: string;
  dateLabel?: string;
  note?: string;
  photoCredit?: string;
  incumbentNote?: string;
  notableAbsence?: string;
  /**
   * `wards` is what a SEAT is measured in. The LGA count describes a
   * governorship and a senatorial district well and a federal constituency
   * badly (2-4); for a state constituency it is almost always the number 1.
   * Both are carried and the card picks by `join.level` — see components/race.
   */
  stats?: {
    lgas?: number;
    wards?: number;
    pollingUnits?: number;
    candidates?: number;
    heldBy?: string;
    /** These figures cover more than this one seat — see SeatInfo. */
    sharedRegister?: boolean;
  };
  candidates: Candidate[];
  others?: Candidate[];
  minors?: Minor[];
  join?: RaceJoin;
  /**
   * What the electoral commission ANNOUNCED, recorded by hand from the returning
   * officer's declaration. Not derivable: IReV publishes photographs of EC8A
   * sheets, never numbers, so there is no endpoint to read this from — an absent
   * block means nobody has recorded the declaration, not that a race is
   * undecided. Kept separate from `candidates` because this is someone else's
   * claim that Hawkeye is citing, not Hawkeye's own count.
   */
  declared?: {
    by?: string;
    date?: string;
    place?: string;
    returningOfficer?: string;
    winner: string;
    party?: string;
    votes?: number;
    runnerUp?: { name: string; party: string; votes: number };
    results?: { party: string; name?: string; votes: number }[];
    lgasWon?: Record<string, number>;
    sources?: string[];
    note?: string;
  };
};

export type Political = {
  note?: string;
  president?: { name: string; party: string };
  governors?: Record<string, string>;
  provisional?: string;
  upcoming?: {
    note?: string;
    elections: { office: string; seats: string; when: string; scope: string }[];
  };
  composition?: {
    asOf?: string;
    note?: string;
    chambers: Record<
      string,
      { label: string; size: number; total: number; parties: Record<string, number> }
    >;
  };
  race2027?: Race;
  raceOsun2026?: Race;
  /** Per-state LGA and polling-unit counts, generated by
   *  backend/scripts/build_state_stats.js. Keyed by display name ("Akwa Ibom"). */
  stateStats?: Record<string, { lgas: number; pollingUnits?: number }>;
};

/** Party brand colours, carried over from the web pages verbatim. */
const PC: Record<string, string> = {
  APC: '#2e7d32',
  PDP: '#c62828',
  LP: '#8bc34a',
  NNPP: '#1565c0',
  APGA: '#f9a825',
  SDP: '#5e35b1',
  ADC: '#00897b',
  YPP: '#ef6c00',
  APM: '#283593',
  NDC: '#2e3192',
  NRM: '#827717',
  ADP: '#455a64',
  AA: '#3e2723',
  BOOT: '#37474f',
  Accord: '#00838f',
  /** INEC's ballot code for Accord — political_data uses it for Osun. */
  A: '#00838f',
};

export const partyColor = (p: string) => PC[p] || '#9aa7a0';

/** Ballot codes that are not the party's common name. */
const PARTY_NAME: Record<string, string> = { A: 'Accord' };

/** Display label for a party code — "A" alone tells a reader nothing. */
export const partyName = (p: string) => (PARTY_NAME[p] ? `${PARTY_NAME[p]} (${p})` : p);

/** One seat in members.json — Hawkeye's own roster (see backend/scripts/build_members.py). */
export type Member = {
  name: string;
  state: string;
  district: string;
  /** Current party, or null when no source we have found publishes one. */
  party: string | null;
  elected?: string | null;
  office?: string | null;
  /** Which source produced the party — shown so any seat can be challenged. */
  source?: string | null;
  changed?: { from?: string; to: string; date?: string; source?: string };
};

export type Chamber = {
  size: number;
  listed: number;
  withParty: number;
  parties: Record<string, number>;
  members: Member[];
};

export type Members = {
  asOf?: string;
  note?: string;
  changesApplied?: number;
  chambers: Record<string, Chamber>;
};

let cache: Promise<{
  data: Political;
  logos: Record<string, string>;
  members: Members | null;
}> | null = null;

export function loadPolitical() {
  if (!cache) {
    cache = Promise.all([
      fetch(`${BASE}/political_data.json`).then((r) => r.json() as Promise<Political>),
      fetch(`${BASE}/logos/manifest.json`)
        .then((r) => r.json() as Promise<Record<string, string>>)
        .catch(() => ({})),
      // The roster is an enrichment: if it fails the screen still renders the
      // committed composition, exactly as it did before this existed.
      fetch(`${BASE}/members.json`)
        .then((r) => r.json() as Promise<Members>)
        .catch(() => null),
    ]).then(([data, logos, members]) => ({ data, logos, members }));
  }
  return cache;
}

export const logoUrl = (logos: Record<string, string>, party: string) =>
  logos[party] ? `${BASE}/${logos[party]}` : null;

const normRegion = (s: string) => String(s ?? '').toLowerCase().replace(/[^a-z0-9]+/g, '');

/**
 * The hand-written race for a (contest, region) pair, or null.
 *
 * Twin of app/race.js:findRace, and derived the same way — from each race's own
 * `join` block rather than from a second list of "races that have screens",
 * which is the kind of thing that is correct the day it is written and wrong a
 * month later. Adding a race with a join makes it reachable from the board on
 * both platforms at once.
 */
export function findRace(
  data: Political | null | undefined,
  contest: string,
  region: string,
): { key: string; race: Race } | null {
  if (!data || !contest || !region) return null;
  const want = normRegion(region);
  for (const [key, value] of Object.entries(data as Record<string, unknown>)) {
    const race = value as Race | undefined;
    const j = race?.join;
    if (!j || j.contest !== contest) continue;
    if (normRegion(j.value) === want) return { key, race: race as Race };
  }
  return null;
}

/**
 * The results tab, showing THIS race — where "See Live Results" goes.
 *
 * Derived from the race's own `join` rather than passed in by each caller: the
 * Osun screen never passed one and the generated state screens never would, so
 * every one of them pushed a bare results tab, which seeds itself with the first
 * contest — the presidency. Twin of app/race.js:resultsHrefFor.
 */
export function resultsHrefFor(race: Race | null | undefined): string {
  const j = race?.join;
  if (!j?.contest || !j.value) return '/(tabs)/results';
  const q = new URLSearchParams({ contest: j.contest, scope: j.value });
  return `/(tabs)/results?${q.toString()}`;
}

/** One seat's register facts, from app/seat_lgas.json. */
export type SeatInfo = {
  state: string;
  lgas: string[];
  pollingUnits: number;
  /**
   * Wards in the seat, counted on the `(state, lga, ward)` TRIPLE. A ward name
   * repeats across LGAs, so counting distinct ward names collapses two into one.
   */
  wards?: number;
  /** Present on the SHA block only, where the table key is "State|Seat". */
  seat?: string;
  /**
   * More than one seat sits on this LGA and the register does not separate
   * them, so these figures cover all of them. Four dense Lagos LGAs elect two
   * federal members each while polling_units records only the LGA — and on the
   * assembly side it is nearly half: 1,005 state seats sit on 768 LGAs, so 240
   * LGAs elect two, three or four members. See backend/scripts/
   * build_seat_lgas.js. The page prints the caveat rather than presenting a
   * shared number as the seat's own.
   */
  sharedRegister?: boolean;
};
/**
 * Keyed by TIER, then by seat. SEN and REP key on the bare seat name, which is
 * unique nationally; **SHA keys on "State|Seat"**, because state-constituency
 * names are not — "Central" and the numbered seats repeat across states.
 */
export type SeatTable = Record<string, Record<string, SeatInfo>>;

let seatCache: Promise<SeatTable> | null = null;

/**
 * seat_lgas.json — 471 seats with their LGA membership, ~46 KB.
 *
 * Fetched only by a seat's own screen and memoised for the run. It is not part
 * of political_data.json on purpose: every screen fetches that, and none of the
 * others has any use for this. A failed fetch clears the cache so the next mount
 * retries rather than replaying one rejection forever.
 */
export function loadSeats(): Promise<SeatTable> {
  if (!seatCache) {
    seatCache = fetch(`${BASE}/seat_lgas.json`)
      .then(async (r) => {
        if (!r.ok) throw new Error(`seat_lgas.json → HTTP ${r.status}`);
        return (await r.json()) as SeatTable;
      })
      .catch((e) => {
        seatCache = null;
        throw e;
      });
  }
  return seatCache;
}

/**
 * A screen for ONE senatorial district or federal constituency. Twin of
 * app/race.js:seatRace, and the destination of a tap on the national board — a
 * map of 109 districts is only worth having if a district goes somewhere.
 */

/**
 * Resolve a seat name against a table of seats: exact first, then by the SET of
 * LGAs the name lists, so ordering and punctuation stop mattering. Ambiguous
 * keys resolve to nothing rather than to a guess — sending a reader to the wrong
 * seat is worse than telling them there is no page.
 *
 * Twin of app/race.js:matchSeatName. Keep the two in step.
 */
function matchSeatName<T>(table: Record<string, T> | undefined, name: string): string | null {
  if (!table || !name) return null;
  const keys = Object.keys(table);
  const exact = keys.find((s) => normRegion(s) === normRegion(name));
  if (exact) return exact;
  const parts = (s: string) => String(s ?? '').split('/').map(normRegion).filter(Boolean).sort().join('|');
  const want = parts(name);
  if (!want) return null;
  const index = new Map<string, string | null>();
  for (const k of keys) {
    const p = parts(k);
    index.set(p, index.has(p) ? null : k);
  }
  const byParts = index.get(want);
  if (byParts) return byParts;

  // THIRD TIER: THE SEAT'S OWN LGA LIST, not its label. The register calls one
  // Delta seat "Warri"; the boundary file spells it out as its three LGAs.
  // Comparing against `lgas` resolves those, because that array is the fact
  // both names are trying to express. Exactly one match, or none.
  const wantSet = new Set(String(name).split('/').map(normRegion).filter(Boolean));
  let hit: string | null = null;
  let hits = 0;
  for (const k of keys) {
    const lgas = (table[k] as { lgas?: string[] })?.lgas ?? [];
    if (!lgas.length) continue;
    // An LGA name can itself contain a slash — Ogun's "Obafemi/Owode" is one
    // LGA — so index each seat's components both whole and split.
    const have = new Set<string>();
    for (const l of lgas) {
      have.add(normRegion(l));
      for (const piece of String(l).split('/')) if (normRegion(piece)) have.add(normRegion(piece));
    }
    if ([...wantSet].every((w) => have.has(w))) { hits++; hit = k; }
  }
  return hits === 1 ? hit : null;
}

/**
 * @param code  the CONTEST code — identity, and what /api/national is keyed by
 * @param tier  the CATEGORY — which seat table to look the name up in. Defaults
 *              to `code`, so the five general contests are unchanged. A
 *              by-election passes REP_BYE_GOMBE_2026 + 'REP': the seat facts
 *              live under REP, the board lives under the by-election's own code,
 *              and merging the two would file a 2026 by-election into the 2027
 *              general election's race — inside a published anchor, permanently.
 */
export function seatRace(
  seats: SeatTable | null | undefined,
  code: string,
  seatName: string,
  contest?: ContestLite | null,
  tier?: string,
): Race | null {
  const table = seats?.[tier || code];
  if (!table || !seatName) return null;
  // Map spellings and register spellings differ on a handful of seats, so the
  // name is resolved rather than trusted.
  // MATCH ON COMPONENTS, NOT THE EXACT STRING. A federal constituency is named
  // by listing its LGAs and the register and the boundary file list them in
  // different orders — the map's "Abaji/Gwagwalada/Kwali/Kuje" is seat_lgas'
  // "Kuje/Abaji/Gwagwalada/Kwali". Exact matching saw two strangers, so 29 of
  // 360 constituencies reached "Hawkeye has no page for this race yet" about a
  // seat we hold every fact for. Web twin: app/race.js:matchSeatName.
  const canon = matchSeatName(table, seatName);
  if (!canon) return null;
  const s = table[canon];
  const senate = (tier || code) === 'SEN';
  return {
    office: `${senate ? 'Senator' : 'House of Representatives'} — ${canon}`,
    election: `${s.state} State · ${senate ? 'Senate' : 'House of Representatives'}`,
    date: contest?.date,
    stats: { lgas: s.lgas.length, wards: s.wards, pollingUnits: s.pollingUnits },
    // A seat the register cannot tell from its neighbour says so, rather than
    // presenting a shared figure as its own.
    note:
      (s.sharedRegister
        ? "INEC's register does not separate this seat from the other constituency in the same LGA, so the LGA and polling-unit figures on this page cover both. "
        : '') +
      'INEC has not published the candidate list for this race yet. Candidates appear here as soon as the official list is out. The map and seat facts on this page come from the electoral register and are current.',
    candidates: [],
    others: [],
    join: {
      contest: code,
      level: senate ? 'senatorial' : 'federal_constituency',
      value: canon,
      state: s.state,
      lgas: s.lgas,
    },
  };
}

/** A contest as GET /api/contests reports it — only the fields a race page needs. */
export type ContestLite = {
  code: string;
  name: string;
  date?: string;
  states?: string[];
  /** The shape a contest behaves as when it is not its own code — see api.ts. */
  tier?: string;
  /** The seats a by-election is confined to. Its presence IS what makes one. */
  constituencies?: string[];
};

/**
 * A governorship screen for a state with no published candidate list — which is
 * every state until INEC publishes one, roughly a month out.
 *
 * Twin of app/race.js:stateRace, and deliberately identical in what it refuses
 * to do: the date comes from the contest catalogue and is ABSENT, not guessed,
 * for the off-cycle states whose next governorship is not in the 2027 general
 * election. Returns null for anything that is not a real state, and for the FCT,
 * which has no governor.
 */
export function stateRace(
  data: Political | null | undefined,
  state: string,
  contest?: ContestLite | null,
): Race | null {
  const pd = data ?? {};
  const known = findRace(pd, 'GOV', state);
  if (known) return known.race; // Osun's written race beats a generated one.
  const canon = Object.keys(pd.stateStats ?? {}).find((s) => normRegion(s) === normRegion(state));
  if (!canon || normRegion(canon) === 'fct') return null;
  const stats = pd.stateStats?.[canon] ?? {};
  const inCycle = !!contest?.states?.some((s) => normRegion(s) === normRegion(canon));
  const held = pd.governors?.[canon];
  return {
    office: `Governor of ${canon} State`,
    election: `${canon} State Governorship Election`,
    date: inCycle ? contest?.date : undefined,
    stats: { ...stats, heldBy: held },
    note: inCycle
      ? 'INEC has not published the candidate list for this race yet. Candidates appear here as soon as the official list is out. The map and seat facts on this page come from the electoral register and are current.'
      : `${canon} votes for governor off the general-election cycle, so this race is not part of the 2027 general election and Hawkeye has no date for it yet. The map and seat facts on this page come from the electoral register and are current.`,
    candidates: [],
    others: [],
    join: { contest: 'GOV', level: 'state', value: canon, state: canon },
  };
}

/** @param what what the reader is being told has no list yet — see the twin
 *  wording in app/race.js, which the parity test compares string for string. */
const seatNote = (what: 'race' | 'by-election') =>
  `INEC has not published the candidate list for this ${what} yet. Candidates ` +
  'appear here as soon as the official list is out. The seat and map on this ' +
  'page come from the electoral register and are current.';

/**
 * A state constituency's figures out of seat_lgas.json. Twin of
 * app/race.js:shaStats.
 *
 * Keyed "State|Seat", unlike SEN and REP which key on the bare name.
 *
 * `sharedRegister` travels with them. Nearly half of the 1,005 state seats sit
 * on an LGA that elects more than one member, and the register cannot say which
 * of them a unit votes in — so those figures describe the LGA, not the race,
 * and the page has to say so rather than print a number that looks specific.
 */
export function shaStats(
  seats: SeatTable | null | undefined,
  state: string,
  seat: string,
): NonNullable<Race['stats']> {
  const t = seats?.SHA ?? {};
  const key = `${state}|${seat}`;
  const canon = t[key] ? key : matchSeatName(t, key);
  let hit = canon ? t[canon] : null;
  /**
   * A BY-ELECTION NAMES ITS LGA, NOT ITS SEAT.
   *
   * `constituencies` is the allowlist the backend gates reports with, and for a
   * state-assembly contest the backend buckets by LGA — so what arrives here is
   * an LGA name. Kano's is "Dawaki Kudu"; the seat is called "Dawakin Kudu". A
   * seat-name lookup cannot bridge that, so it missed and the card fell back to
   * `{ lgas: 1 }` — the exact "1 LGAs" this function exists to remove, on the
   * one screen most likely to be read.
   *
   * Where the LGA elects several members every one of those rows carries the
   * LGA's own figures (checked: identical across all 240 shared groups), so the
   * first is as good as any and `sharedRegister` is already set on it.
   */
  if (!hit) hit = assemblySeatsInLga(seats, state, seat)[0] ?? null;
  if (!hit) return { lgas: 1 };
  return {
    lgas: (hit.lgas ?? []).length,
    wards: hit.wards,
    pollingUnits: hit.pollingUnits,
    sharedRegister: !!hit.sharedRegister,
  };
}

/**
 * A BY-ELECTION'S SCREEN. Twin of app/race.js:byElectionRace.
 *
 * A by-election is a race in the same category as the general election for that
 * seat — a House by-election is a House race — so it reuses the same builders.
 * What it must never do is share the general election's CONTEST CODE:
 * `join.contest` is what /api/national is keyed by and what the ledger
 * partitions a race's subchain on, so filing a 2026 by-election under `REP`
 * would merge it with the 2027 general election for the same seat, inside a
 * published anchor, permanently.
 *
 * The seat's name comes from the contest itself. `constituencies` is the
 * allowlist the backend gates reports with (services/scope.js contestGate), so
 * the screen and the gate cannot describe different places.
 */
export function byElectionRace(
  contest: ContestLite | null | undefined,
  seats: SeatTable | null | undefined,
  political: Political | null | undefined,
): Race | null {
  if (!contest) return null;
  const tier = contest.tier || contest.code;
  const seat = (contest.constituencies ?? [])[0];
  const state = (contest.states ?? [])[0];
  if (!seat) return null;

  if (tier === 'SEN' || tier === 'REP') {
    const r = seatRace(seats, contest.code, seat, contest, tier);
    if (r) r.election = `${state} State · ${contest.name}`;
    return r;
  }
  if (tier === 'GOV') return stateRace(political, state, contest);
  if (tier !== 'SHA') return null;

  // REAL FIGURES, not the number 1. This was `lgas: constituencies.length`,
  // which is always 1 for a by-election, so the card read "1 LGAs" and said
  // nothing. The seat table carries state constituencies now.
  const stats = shaStats(seats, state, seat);
  return {
    office: `${seat} State Constituency — ${state} State`,
    election: `${state} State · ${contest.name}`,
    date: contest.date || undefined,
    stats,
    note:
      (stats.sharedRegister
        ? "This LGA elects more than one state member, and INEC's register does " +
          'not separate them, so the ward and polling-unit figures on this page ' +
          'cover every seat in the LGA rather than this one alone. '
        : '') + seatNote('by-election'),
    candidates: [],
    others: [],
    join: {
      contest: contest.code,
      // 'lga' because that is the level the backend buckets a state-assembly
      // contest by — state-assembly constituencies are not in the register.
      level: 'lga',
      value: seat,
      state,
      lgas: contest.constituencies ?? [],
    },
  };
}

/**
 * A STATE CONSTITUENCY'S SCREEN. Twin of app/race.js:assemblyRace.
 *
 * State-assembly seats are not a column in the register — that is why the
 * backend buckets SHA reports by LGA — so everything here comes from the SHA
 * block of seat_lgas.json, built from the seat catalogue.
 *
 * There are 1,005 of them, which is why they are reached by route param and
 * from the board rather than listed anywhere: the same treatment the 109
 * senatorial districts and 366 federal constituencies already get.
 */
export function assemblyRace(
  seats: SeatTable | null | undefined,
  state: string,
  seat: string,
  contest?: ContestLite | null,
): Race | null {
  const table = seats?.SHA ?? {};
  const key = `${state}|${seat}`;
  const canon = table[key] ? key : matchSeatName(table, key);
  if (!canon) return null;
  const s = table[canon];
  return {
    office: `${s.seat ?? seat} State Constituency`,
    election: `${s.state} State · House of Assembly`,
    date: contest?.date,
    stats: { lgas: (s.lgas ?? []).length, wards: s.wards, pollingUnits: s.pollingUnits },
    note:
      (s.sharedRegister
        ? `${(s.lgas ?? []).join(', ')} elects more than one state member, and INEC's ` +
          'register does not separate them, so the ward and polling-unit figures on this ' +
          'page cover every seat in that LGA rather than this one alone. '
        : '') + seatNote('race'),
    candidates: [],
    others: [],
    join: {
      contest: contest?.code ?? 'SHA',
      level: 'lga',
      value: (s.lgas ?? [])[0] ?? (s.seat ?? seat),
      state: s.state,
      lgas: s.lgas ?? [],
    },
  };
}

/**
 * Every state constituency in one state, for the picker. Sorted by name so the
 * list is stable; a state has 24-40 of them, which is a readable screen.
 */
export function assemblySeats(
  seats: SeatTable | null | undefined,
  state: string,
): SeatInfo[] {
  const table = seats?.SHA ?? {};
  return Object.keys(table)
    .filter((k) => normRegion(k.split('|')[0]) === normRegion(state))
    .map((k) => table[k])
    .sort((a, b) => String(a.seat).localeCompare(String(b.seat)));
}

/**
 * The seats sitting on one LGA.
 *
 * The SHA board buckets by LGA, so a tap on it names an LGA and not a seat —
 * and 240 of the 768 LGAs elect two, three or four members. Returning the LIST
 * rather than the first one is what stops the board sending a reader to a race
 * they did not tap on.
 */
export function assemblySeatsInLga(
  seats: SeatTable | null | undefined,
  state: string,
  lga: string,
): SeatInfo[] {
  return assemblySeats(seats, state).filter((s) =>
    (s.lgas ?? []).some((l) => normRegion(l) === normRegion(lga)),
  );
}

/**
 * A SEAT LISTS ITS FIELD; A REGION PROFILES IT.
 *
 * The presidency and a governorship are races a reader follows as a contest
 * between named people — so they keep the front-runner cards, the full ballot
 * and the quick-compare table. A Senate, House or state-assembly seat is not
 * read that way: there are 1,480 of them, the field is a list of names, and
 * there is no per-candidate prose to profile or compare. Giving one of those the
 * presidential treatment would produce a screen of cards with "—" in every field
 * and a compare table whose five columns are all empty.
 *
 * So a seat gets ONE section, "Declared candidates", in the same compact row
 * format the presidential screen already uses for "Other declared candidates".
 *
 * Keyed off `join.level`, the same field the map, the board and the stat bar key
 * on, so a screen cannot draw itself as one kind of race and list itself as
 * another. No join at all means the presidency, which has none.
 *
 * A FUNCTION, not an expression inside the component, because the web twin needs
 * the identical answer and a rule buried in JSX cannot be compared to one buried
 * in template strings. Twin: app/race.js:seatFieldOf, held against this one by
 * tests/native_race_parity_test.mjs.
 */
export function seatFieldOf(race: Race | null | undefined): boolean {
  const lvl = race?.join?.level;
  return lvl === 'senatorial' || lvl === 'federal_constituency' || lvl === 'lga';
}

/** A row in a seat's single candidate list — a Candidate, or a Minor's `meta`. */
export type FieldEntry = Candidate & { meta?: string };

/**
 * Every declared name on a seat's screen, in one list.
 *
 * `candidates`/`others`/`minors` are three shapes of the same fact and a seat
 * has no reason to separate them — merging is what lets one heading be honest
 * about being the whole field. Sorted by party, so the order is not a ranking.
 */
export function wholeFieldOf(race: Race | null | undefined): FieldEntry[] {
  return [
    ...(race?.candidates ?? []),
    ...(race?.others ?? []),
    ...(race?.minors ?? []),
  ].sort((a, b) => String(a.party).localeCompare(String(b.party)));
}

/**
 * Absolutise a candidate photo path from political_data.json.
 *
 * The file stores site-relative paths ("photos/candidates/tinubu.jpg") because
 * the web pages resolve them against the document. React Native has no document,
 * so a bare relative string is not a loadable URI and the <Image> silently
 * renders nothing — which is exactly how every candidate avatar came out blank.
 * Absolute URLs are passed through untouched, so the JSON can move to a CDN
 * without a code change.
 */
export const photoUrl = (photo?: string | null): string | undefined => {
  if (!photo) return undefined;
  return /^https?:\/\//i.test(photo) ? photo : `${BASE}/${photo.replace(/^\/+/, '')}`;
};
