/**
 * political_data.json + the party-emblem manifest — the same two static files
 * the website reads. Fetched once per app run and memoised: the data changes on
 * the order of weeks, and three screens want it.
 */
const BASE = 'https://hawkeye.com.ng';

export type Candidate = {
  name: string;
  party: string;
  initials?: string;
  line?: string;
  home?: string;
  bids?: string;
  status?: string;
  incumbent?: boolean;
  photo?: string;
};

export type Minor = { name: string; party: string; meta?: string };

/**
 * Where a race sits on the map — the same block app/race.js reads.
 *
 * A race declares its own seat, so the region -> race-page index can be derived
 * rather than kept as a second list beside the data. `level` picks the geometry:
 * a governorship is a `state` (drawn as its LGAs), a Senate seat is
 * `senatorial`, a House seat `federal_constituency`.
 */
export type RaceJoin = {
  contest?: string;
  level: 'state' | 'senatorial' | 'federal_constituency';
  value: string;
  state?: string;
  lgas?: string[];
};

export type Race = {
  asOf?: string;
  office?: string;
  election?: string;
  date?: string;
  /** Verbatim date label when there is no fixed ISO date yet (e.g. the 2027
   *  presidential day, shown as dateText "2027" / dateLabel "Election year"). */
  dateText?: string;
  dateLabel?: string;
  note?: string;
  photoCredit?: string;
  incumbentNote?: string;
  notableAbsence?: string;
  stats?: { lgas?: number; pollingUnits?: number; candidates?: number; heldBy?: string };
  candidates: Candidate[];
  others?: Candidate[];
  minors?: Minor[];
  join?: RaceJoin;
  /**
   * What the electoral commission ANNOUNCED, recorded by hand from the returning
   * officer's declaration. Not derivable: IReV publishes photographs of EC8A
   * sheets, never numbers, so there is no endpoint to read this from — an absent
   * block means nobody has recorded the declaration, not that a race is
   * undecided. Kept separate from `candidates` because this is someone else's
   * claim that Hawkeye is citing, not Hawkeye's own count.
   */
  declared?: {
    by?: string;
    date?: string;
    place?: string;
    returningOfficer?: string;
    winner: string;
    party?: string;
    votes?: number;
    runnerUp?: { name: string; party: string; votes: number };
    results?: { party: string; name?: string; votes: number }[];
    lgasWon?: Record<string, number>;
    sources?: string[];
    note?: string;
  };
};

export type Political = {
  note?: string;
  president?: { name: string; party: string };
  governors?: Record<string, string>;
  provisional?: string;
  upcoming?: {
    note?: string;
    elections: { office: string; seats: string; when: string; scope: string }[];
  };
  composition?: {
    asOf?: string;
    note?: string;
    chambers: Record<
      string,
      { label: string; size: number; total: number; parties: Record<string, number> }
    >;
  };
  race2027?: Race;
  raceOsun2026?: Race;
  /** Per-state LGA and polling-unit counts, generated by
   *  backend/scripts/build_state_stats.js. Keyed by display name ("Akwa Ibom"). */
  stateStats?: Record<string, { lgas: number; pollingUnits?: number }>;
};

/** Party brand colours, carried over from the web pages verbatim. */
const PC: Record<string, string> = {
  APC: '#2e7d32',
  PDP: '#c62828',
  LP: '#8bc34a',
  NNPP: '#1565c0',
  APGA: '#f9a825',
  SDP: '#5e35b1',
  ADC: '#00897b',
  YPP: '#ef6c00',
  APM: '#283593',
  NDC: '#2e3192',
  NRM: '#827717',
  ADP: '#455a64',
  AA: '#3e2723',
  BOOT: '#37474f',
  Accord: '#00838f',
  /** INEC's ballot code for Accord — political_data uses it for Osun. */
  A: '#00838f',
};

export const partyColor = (p: string) => PC[p] || '#9aa7a0';

/** Ballot codes that are not the party's common name. */
const PARTY_NAME: Record<string, string> = { A: 'Accord' };

/** Display label for a party code — "A" alone tells a reader nothing. */
export const partyName = (p: string) => (PARTY_NAME[p] ? `${PARTY_NAME[p]} (${p})` : p);

/** One seat in members.json — Hawkeye's own roster (see backend/scripts/build_members.py). */
export type Member = {
  name: string;
  state: string;
  district: string;
  /** Current party, or null when no source we have found publishes one. */
  party: string | null;
  elected?: string | null;
  office?: string | null;
  /** Which source produced the party — shown so any seat can be challenged. */
  source?: string | null;
  changed?: { from?: string; to: string; date?: string; source?: string };
};

export type Chamber = {
  size: number;
  listed: number;
  withParty: number;
  parties: Record<string, number>;
  members: Member[];
};

export type Members = {
  asOf?: string;
  note?: string;
  changesApplied?: number;
  chambers: Record<string, Chamber>;
};

let cache: Promise<{
  data: Political;
  logos: Record<string, string>;
  members: Members | null;
}> | null = null;

export function loadPolitical() {
  if (!cache) {
    cache = Promise.all([
      fetch(`${BASE}/political_data.json`).then((r) => r.json() as Promise<Political>),
      fetch(`${BASE}/logos/manifest.json`)
        .then((r) => r.json() as Promise<Record<string, string>>)
        .catch(() => ({})),
      // The roster is an enrichment: if it fails the screen still renders the
      // committed composition, exactly as it did before this existed.
      fetch(`${BASE}/members.json`)
        .then((r) => r.json() as Promise<Members>)
        .catch(() => null),
    ]).then(([data, logos, members]) => ({ data, logos, members }));
  }
  return cache;
}

export const logoUrl = (logos: Record<string, string>, party: string) =>
  logos[party] ? `${BASE}/${logos[party]}` : null;

const normRegion = (s: string) => String(s ?? '').toLowerCase().replace(/[^a-z0-9]+/g, '');

/**
 * The hand-written race for a (contest, region) pair, or null.
 *
 * Twin of app/race.js:findRace, and derived the same way — from each race's own
 * `join` block rather than from a second list of "races that have screens",
 * which is the kind of thing that is correct the day it is written and wrong a
 * month later. Adding a race with a join makes it reachable from the board on
 * both platforms at once.
 */
export function findRace(
  data: Political | null | undefined,
  contest: string,
  region: string,
): { key: string; race: Race } | null {
  if (!data || !contest || !region) return null;
  const want = normRegion(region);
  for (const [key, value] of Object.entries(data as Record<string, unknown>)) {
    const race = value as Race | undefined;
    const j = race?.join;
    if (!j || j.contest !== contest) continue;
    if (normRegion(j.value) === want) return { key, race: race as Race };
  }
  return null;
}

/**
 * The results tab, showing THIS race — where "See Live Results" goes.
 *
 * Derived from the race's own `join` rather than passed in by each caller: the
 * Osun screen never passed one and the generated state screens never would, so
 * every one of them pushed a bare results tab, which seeds itself with the first
 * contest — the presidency. Twin of app/race.js:resultsHrefFor.
 */
export function resultsHrefFor(race: Race | null | undefined): string {
  const j = race?.join;
  if (!j?.contest || !j.value) return '/(tabs)/results';
  const q = new URLSearchParams({ contest: j.contest, scope: j.value });
  return `/(tabs)/results?${q.toString()}`;
}

/** One seat's register facts, from app/seat_lgas.json. */
export type SeatInfo = {
  state: string;
  lgas: string[];
  pollingUnits: number;
  /**
   * Two federal seats share this LGA and the register does not separate them,
   * so these figures cover both. Four dense Lagos LGAs elect two members each
   * while polling_units records only the LGA — see backend/scripts/
   * build_seat_lgas.js. The page prints the caveat rather than presenting a
   * shared number as the seat's own.
   */
  sharedRegister?: boolean;
};
export type SeatTable = Record<string, Record<string, SeatInfo>>;

let seatCache: Promise<SeatTable> | null = null;

/**
 * seat_lgas.json — 471 seats with their LGA membership, ~46 KB.
 *
 * Fetched only by a seat's own screen and memoised for the run. It is not part
 * of political_data.json on purpose: every screen fetches that, and none of the
 * others has any use for this. A failed fetch clears the cache so the next mount
 * retries rather than replaying one rejection forever.
 */
export function loadSeats(): Promise<SeatTable> {
  if (!seatCache) {
    seatCache = fetch(`${BASE}/seat_lgas.json`)
      .then(async (r) => {
        if (!r.ok) throw new Error(`seat_lgas.json → HTTP ${r.status}`);
        return (await r.json()) as SeatTable;
      })
      .catch((e) => {
        seatCache = null;
        throw e;
      });
  }
  return seatCache;
}

/**
 * A screen for ONE senatorial district or federal constituency. Twin of
 * app/race.js:seatRace, and the destination of a tap on the national board — a
 * map of 109 districts is only worth having if a district goes somewhere.
 */

/**
 * Resolve a seat name against a table of seats: exact first, then by the SET of
 * LGAs the name lists, so ordering and punctuation stop mattering. Ambiguous
 * keys resolve to nothing rather than to a guess — sending a reader to the wrong
 * seat is worse than telling them there is no page.
 *
 * Twin of app/race.js:matchSeatName. Keep the two in step.
 */
function matchSeatName<T>(table: Record<string, T> | undefined, name: string): string | null {
  if (!table || !name) return null;
  const keys = Object.keys(table);
  const exact = keys.find((s) => normRegion(s) === normRegion(name));
  if (exact) return exact;
  const parts = (s: string) => String(s ?? '').split('/').map(normRegion).filter(Boolean).sort().join('|');
  const want = parts(name);
  if (!want) return null;
  const index = new Map<string, string | null>();
  for (const k of keys) {
    const p = parts(k);
    index.set(p, index.has(p) ? null : k);
  }
  const byParts = index.get(want);
  if (byParts) return byParts;

  // THIRD TIER: THE SEAT'S OWN LGA LIST, not its label. The register calls one
  // Delta seat "Warri"; the boundary file spells it out as its three LGAs.
  // Comparing against `lgas` resolves those, because that array is the fact
  // both names are trying to express. Exactly one match, or none.
  const wantSet = new Set(String(name).split('/').map(normRegion).filter(Boolean));
  let hit: string | null = null;
  let hits = 0;
  for (const k of keys) {
    const lgas = (table[k] as { lgas?: string[] })?.lgas ?? [];
    if (!lgas.length) continue;
    // An LGA name can itself contain a slash — Ogun's "Obafemi/Owode" is one
    // LGA — so index each seat's components both whole and split.
    const have = new Set<string>();
    for (const l of lgas) {
      have.add(normRegion(l));
      for (const piece of String(l).split('/')) if (normRegion(piece)) have.add(normRegion(piece));
    }
    if ([...wantSet].every((w) => have.has(w))) { hits++; hit = k; }
  }
  return hits === 1 ? hit : null;
}

export function seatRace(
  seats: SeatTable | null | undefined,
  code: 'SEN' | 'REP',
  seatName: string,
  contest?: ContestLite | null,
): Race | null {
  const table = seats?.[code];
  if (!table || !seatName) return null;
  // Map spellings and register spellings differ on a handful of seats, so the
  // name is resolved rather than trusted.
  // MATCH ON COMPONENTS, NOT THE EXACT STRING. A federal constituency is named
  // by listing its LGAs and the register and the boundary file list them in
  // different orders — the map's "Abaji/Gwagwalada/Kwali/Kuje" is seat_lgas'
  // "Kuje/Abaji/Gwagwalada/Kwali". Exact matching saw two strangers, so 29 of
  // 360 constituencies reached "Hawkeye has no page for this race yet" about a
  // seat we hold every fact for. Web twin: app/race.js:matchSeatName.
  const canon = matchSeatName(table, seatName);
  if (!canon) return null;
  const s = table[canon];
  const senate = code === 'SEN';
  return {
    office: `${senate ? 'Senator' : 'House of Representatives'} — ${canon}`,
    election: `${s.state} State · ${senate ? 'Senate' : 'House of Representatives'}`,
    date: contest?.date,
    stats: { lgas: s.lgas.length, pollingUnits: s.pollingUnits },
    // A seat the register cannot tell from its neighbour says so, rather than
    // presenting a shared figure as its own.
    note:
      (s.sharedRegister
        ? "INEC's register does not separate this seat from the other constituency in the same LGA, so the LGA and polling-unit figures on this page cover both. "
        : '') +
      'INEC has not published the candidate list for this race yet. Candidates appear here as soon as the official list is out. The map and seat facts on this page come from the electoral register and are current.',
    candidates: [],
    others: [],
    join: {
      contest: code,
      level: senate ? 'senatorial' : 'federal_constituency',
      value: canon,
      state: s.state,
      lgas: s.lgas,
    },
  };
}

/** A contest as GET /api/contests reports it — only the fields a race page needs. */
export type ContestLite = { code: string; name: string; date?: string; states?: string[] };

/**
 * A governorship screen for a state with no published candidate list — which is
 * every state until INEC publishes one, roughly a month out.
 *
 * Twin of app/race.js:stateRace, and deliberately identical in what it refuses
 * to do: the date comes from the contest catalogue and is ABSENT, not guessed,
 * for the off-cycle states whose next governorship is not in the 2027 general
 * election. Returns null for anything that is not a real state, and for the FCT,
 * which has no governor.
 */
export function stateRace(
  data: Political | null | undefined,
  state: string,
  contest?: ContestLite | null,
): Race | null {
  const pd = data ?? {};
  const known = findRace(pd, 'GOV', state);
  if (known) return known.race; // Osun's written race beats a generated one.
  const canon = Object.keys(pd.stateStats ?? {}).find((s) => normRegion(s) === normRegion(state));
  if (!canon || normRegion(canon) === 'fct') return null;
  const stats = pd.stateStats?.[canon] ?? {};
  const inCycle = !!contest?.states?.some((s) => normRegion(s) === normRegion(canon));
  const held = pd.governors?.[canon];
  return {
    office: `Governor of ${canon} State`,
    election: `${canon} State Governorship Election`,
    date: inCycle ? contest?.date : undefined,
    stats: { ...stats, heldBy: held },
    note: inCycle
      ? 'INEC has not published the candidate list for this race yet. Candidates appear here as soon as the official list is out. The map and seat facts on this page come from the electoral register and are current.'
      : `${canon} votes for governor off the general-election cycle, so this race is not part of the 2027 general election and Hawkeye has no date for it yet. The map and seat facts on this page come from the electoral register and are current.`,
    candidates: [],
    others: [],
    join: { contest: 'GOV', level: 'state', value: canon, state: canon },
  };
}

/**
 * Absolutise a candidate photo path from political_data.json.
 *
 * The file stores site-relative paths ("photos/candidates/tinubu.jpg") because
 * the web pages resolve them against the document. React Native has no document,
 * so a bare relative string is not a loadable URI and the <Image> silently
 * renders nothing — which is exactly how every candidate avatar came out blank.
 * Absolute URLs are passed through untouched, so the JSON can move to a CDN
 * without a code change.
 */
export const photoUrl = (photo?: string | null): string | undefined => {
  if (!photo) return undefined;
  return /^https?:\/\//i.test(photo) ? photo : `${BASE}/${photo.replace(/^\/+/, '')}`;
};
