/**
 * MULTIPART UPLOAD WITH REAL BYTE PROGRESS.
 *
 * WHY THIS EXISTS. An incident can carry four attachments including video, and
 * on a Nigerian mobile network that upload can run for a minute or more. The
 * screen said "Submitting…" in the same small line every other message uses,
 * which after thirty seconds is indistinguishable from a hung app — and the one
 * thing a reporter must not do is give up and re-file, or close the app.
 *
 * WHY NOT fetch(). fetch has no upload-progress event, in any runtime. There is
 * no way to make it report bytes sent. XMLHttpRequest does, through
 * `upload.onprogress`, and React Native implements it against its own networking
 * stack — which streams the file off disk rather than reading it into memory.
 * That last point is what rules out the obvious alternative of reading each file
 * into a real Blob so fetch can measure it: four videos in memory at once is an
 * OOM on exactly the low-end handsets this app is aimed at.
 *
 * THE PART SHAPE IS DIFFERENT HERE, AND THAT IS DELIBERATE.
 * lib/submit.ts's filePart() returns an object exposing bytes(), because Expo
 * SDK 54+ ships a spec-compliant FormData converter for fetch that rejects the
 * classic React Native part. XHR does NOT go through that converter — it uses
 * RN's own FormData serialiser, which wants exactly the classic
 * { uri, name, type } shape and rejects the bytes() object. So the two
 * transports genuinely need two shapes; they are not a duplication that can be
 * collapsed, and each is commented where it lives.
 *
 * HOW IT FAILS. It rejects, like fetch would. The caller is expected to fall
 * back to its existing fetch path on a rejection — see report/incident.tsx.
 * That matters more than usual: the part-shape assumption above cannot be
 * verified anywhere but on a device, so a wrong guess must degrade to the
 * behaviour that already worked rather than break submission.
 */

export type UploadProgress = {
  /** Bytes sent so far. */
  sent: number;
  /** Total bytes, or null when the platform cannot say. */
  total: number | null;
  /** 0-100, or null when the total is unknown. */
  pct: number | null;
};

/** A part in the shape RN's own FormData serialiser understands. */
export function xhrFilePart(uri: string, name: string, type: string) {
  return { uri, name, type } as unknown as Blob;
}

export type UploadResult = {
  ok: boolean;
  status: number;
  /** Parsed body, or null when the response was not JSON. */
  json: () => unknown;
  text: string;
};

/**
 * POST a multipart form, reporting bytes as they go.
 *
 * Resolves for ANY HTTP answer, including a 4xx/5xx — the caller decides what a
 * status means, exactly as it would with fetch. Rejects only when nothing
 * reached the server (network error, timeout, abort).
 */
export function uploadWithProgress(opts: {
  url: string;
  form: FormData;
  headers?: Record<string, string>;
  onProgress?: (p: UploadProgress) => void;
  /** Milliseconds. 0 disables. A stalled upload should not hold the screen for ever. */
  timeoutMs?: number;
}): Promise<UploadResult> {
  const { url, form, headers = {}, onProgress, timeoutMs = 180000 } = opts;
  return new Promise((resolve, reject) => {
    const xhr = new XMLHttpRequest();
    xhr.open('POST', url);
    for (const [k, v] of Object.entries(headers)) xhr.setRequestHeader(k, v);
    // NEVER set Content-Type by hand for multipart: the boundary is generated by
    // the serialiser and a hand-written header loses it, which the server then
    // reads as a malformed body.
    if (timeoutMs > 0) xhr.timeout = timeoutMs;

    if (onProgress && xhr.upload) {
      /**
       * `loaded` CAN EXCEED `total`, and did — a screen recording showed
       * "Uploading 100% — 54.5 MB of 27.3 MB", almost exactly twice the body.
       *
       * The bytes are real: the server rejects an oversize part early and
       * closes, and the HTTP client underneath replays the request body, while
       * this one XHR keeps counting across both attempts. Whatever the cause,
       * a progress bar that reports more than was ever going to be sent is
       * telling the observer something false at the moment they are deciding
       * whether to wait — so it is clamped at the total, and `pct` was already
       * clamped, which is why the percentage sat at a plausible 100 while the
       * byte count ran away underneath it.
       *
       * The real fix is upstream: the file is now measured before it is sent,
       * so a body this size does not leave the phone. This keeps the display
       * honest if anything ever gets past that.
       */
      xhr.upload.onprogress = (e: ProgressEvent) => {
        const total = e.lengthComputable ? e.total : null;
        const sent = total ? Math.min(e.loaded, total) : e.loaded;
        onProgress({
          sent,
          total,
          pct: total ? Math.max(0, Math.min(100, Math.round((sent / total) * 100))) : null,
        });
      };
    }

    xhr.onload = () => {
      const text = typeof xhr.responseText === 'string' ? xhr.responseText : '';
      resolve({
        ok: xhr.status >= 200 && xhr.status < 300,
        status: xhr.status,
        text,
        json: () => { try { return JSON.parse(text); } catch { return null; } },
      });
    };
    xhr.onerror = () => reject(new Error('network error'));
    xhr.ontimeout = () => reject(new Error('upload timed out'));
    xhr.onabort = () => reject(new Error('aborted'));

    try {
      xhr.send(form as unknown as Document);
    } catch (e) {
      reject(e instanceof Error ? e : new Error(String(e)));
    }
  });
}

/** "2.4 MB" / "812 KB" — for a progress line a person reads mid-upload. */
export function humanBytes(n: number): string {
  if (!Number.isFinite(n) || n < 0) return '';
  if (n < 1024) return `${n} B`;
  if (n < 1024 * 1024) return `${Math.round(n / 1024)} KB`;
  return `${(n / (1024 * 1024)).toFixed(1)} MB`;
}
