/**
 * EVERY KEY THE CODE CALLS MUST EXIST IN THE BUNDLES.
 *
 * This exists because the app rendered "N.APP.TABS.INDEX.UPCOMING-ELECTION" to a
 * user, on the home screen, in place of a sentence.
 *
 * HOW THAT HAPPENED, because the shape of it matters more than the instance.
 * translate() falls through the chosen bundle, then English, then RETURNS THE
 * KEY. I keyed source files and reasoned that an untranslated key would fall
 * back to English and therefore be safe to land before the translations. That
 * is true only if the key is in the ENGLISH bundle — and the English bundle is
 * generated by the same builder that REFUSES TO WRITE while any language is
 * missing a key. So keying the source made the builder refuse, the refusal left
 * every bundle stale, and the fallback chain ran off its end into the raw key.
 * Each piece behaved correctly and the composition shipped a broken screen.
 *
 * A missing key is invisible in review, invisible to tsc, and invisible to the
 * bundle builder — which only compares the catalogue against the bundles and
 * never looks at what the code actually calls. This closes that gap from the
 * other side: it reads the CALL SITES.
 *
 *   node scripts/i18n/native_keys_resolve.mjs
 *   node scripts/i18n/native_keys_resolve.mjs --control
 */
import fs from 'node:fs';
import path from 'node:path';

const ROOT = '/home/elrio/hawkeye';
const SRC = path.join(ROOT, 'native/src');
const CONTROL = process.argv.includes('--control');

const bundles = {};
for (const code of ['en', 'ha', 'ig', 'yo']) {
  bundles[code] = JSON.parse(fs.readFileSync(path.join(SRC, `lib/i18n/${code}.json`), 'utf8'));
}

function walk(dir, out = []) {
  for (const e of fs.readdirSync(dir, { withFileTypes: true })) {
    if (e.isDirectory()) {
      if (e.name === 'node_modules' || e.name === '.expo') continue;
      walk(path.join(dir, e.name), out);
    } else if (e.name.endsWith('.tsx') || e.name.endsWith('.ts')) out.push(path.join(dir, e.name));
  }
  return out;
}

const calls = new Map();
const computed = new Set();  // literal halves of concatenated keys            // key -> [file:line]
for (const f of walk(SRC)) {
  const text = fs.readFileSync(f, 'utf8');
  const lines = text.split('\n');
  lines.forEach((ln, i) => {
    for (const m of ln.matchAll(/\bi18nT\(\s*'([^']+)'(\s*\+)?/g)) {
      // A COMPUTED KEY IS NOT A MISSING KEY. `i18nT('n.app.tabs.more.' + scheme)`
      // has a literal half that is not a key on its own; reading it as one made
      // this check report a false missing, and a checker that cries wolf gets
      // ignored on the day it is right.
      if (m[2]) { computed.add(m[1]); continue; }
      const where = `${f.replace(SRC + '/', '')}:${i + 1}`;
      if (!calls.has(m[1])) calls.set(m[1], []);
      calls.get(m[1]).push(where);
    }
  });
}

if (CONTROL) calls.set('n.this.key.does.not.exist', ['control:0']);

const missing = [];
const missingComputed = [];
for (const [k, where] of calls) {
  const absent = ['en', 'ha', 'ig', 'yo'].filter((c) => !(k in bundles[c]));
  if (absent.length) missing.push({ k, where, absent });
}

console.log(`  ${calls.size} distinct keys called from ${walk(SRC).length} files`);
if (computed.size) {
  console.log(`  ${computed.size} computed key prefix(es), checked by hand: ${[...computed].join(', ')}`);
  for (const p of computed) {
    const found = Object.keys(bundles.en).filter((k) => k.startsWith(p));
    console.log(`    ${p}* resolves to ${found.length} key(s): ${found.slice(0, 6).join(', ')}`);
    if (!found.length) missingComputed.push(p);
  }
}
console.log(`  bundle sizes: ${['en', 'ha', 'ig', 'yo'].map((c) => `${c}=${Object.keys(bundles[c]).length}`).join('  ')}`);

if (missing.length) {
  console.log(`\n  KEYS THAT WOULD RENDER AS THEMSELVES (${missing.length}):`);
  for (const m of missing.slice(0, 15)) {
    console.log(`    ${m.k}`);
    console.log(`        missing from: ${m.absent.join(', ')}   called at ${m.where[0]}`);
  }
}

if (CONTROL) {
  const caught = missing.some((m) => m.k === 'n.this.key.does.not.exist');
  console.log(caught
    ? '\nCONTROL PASSED — a key with no bundle entry is caught'
    : '\nCONTROL FAILED — a missing key went unnoticed');
  process.exit(caught ? 0 : 1);
}

console.log(missing.length
  ? '\nFAILED — the app would print these keys to a user'
  : '\nALL KEYS RESOLVE in all four languages');
process.exit(missing.length || missingComputed.length ? 1 : 0);
